### ISSUE TITLE
Front image with better quality

### ISSUE THREAD

**Issue by hazed0m** [dandygithub/kodi#67]
Can you get src link from parent href with full quality image, because on 4k tv it looks weird with this preview picture

![image](https://user-images.githubusercontent.com/41749146/123553866-32a20300-d786-11eb-955a-0e6c07ec22f6.png)

**Comment by DesSolo** [comment]
Yes, you are right about the quality. But in order to display the image in good quality, you will have to go to the detailed video viewing. It will take a very long time and will load the video server with additional requests.
If you know how to get a high quality image from the video list - please reopen this issues.

**Comment by hazed0m** [comment]
@DesSolo But your src in image opened without video preview? I mean, image which added on link tag and img tag is different and that src in image tag is have cool quality for our solving

**Comment by DesSolo** [comment]
The parser requests a list view (for example /?filter=popular). And there it takes links to images. There is no better quality. I don't like it either :)
